Update Jenkinsfile2.0

diff --git a/Jenkinsfile2.0 b/Jenkinsfile2.0
--- a/Jenkinsfile2.0
+++ b/Jenkinsfile2.0
@@ -99,6 +99,12 @@ pipeline {
                     cd build
                     cmake .. -DGTEST_SRC_DIR=../../tests/gtest
                     cmake --build .
+                    
+                    # Verificăm dacă executabilul a fost creat
+                    if [ ! -f test_main ]; then
+                        echo "test_main not found"
+                        exit 1
+                    fi
                     '''
                 }
             }
